### ISSUE TITLE
Implement Postgres backend

### ISSUE THREAD

**Issue by arusahni** [arusahni/klaxer#12]
We're currently using SQLite.  This works well, but if we want to go serverless, we'll need to store data in RDS. Implement a Postgres storage backend that the user can switch to via a config setting.

**Comment by abaruchi** [comment]
Hi. Could you assign this issue to me please. I'll try to help on this.

**Comment by arusahni** [comment]
@abaruchi Hi! Sure thing.  This is a bit of an open ended task, so don't be afraid to add more to the PR as you see fit.

**Comment by arusahni** [comment]
(Looks like I can't add non-committers as assignees. The comment will suffice 👍 )
